//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;

public interface IKillable<T>{
	void Kill(float Health, T actor);
}

public interface IDamagable<T>{
	void Damage(T damageTaken);
}

public interface IDestructible<T>{
	void Destroy(T item);
}

public interface IItems<T>{
	void pickUpItem(T inventory);
	void dropItem(T inventory);
}

public interface IExperience{
	void getExp(int orbs);
	void gainLevel(int level);
}
