//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
namespace AssemblyCSharp
{
	
	public interface IKillable<T>{
		void Kill(T Health);
	}
	
	public interface IDamagable<T>{
		void takeDamage(T damageTaken);
	}
	
	public interface IDestructible<T>{
		void Destroy(T item);
	}
	
	public interface IItems{
		void pickUpItem(ItemData item);
		void dropItem(List<ItemData> inventory);
	}
	


	public interface IExperience{
        void dropExp(int orbs);
		void gainExp(Experience orbs);
		void gainLevel(int level);
	}

	public interface IVendor{
		void openShop(GameObject player);
	}


}

